apiVersion: v1
kind: Service
metadata:
  labels:
    app: demoinit
  name: demoinit
spec:
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demoinit
  type: NodePort
